
@uriMensaje = http://localhost:8000/api/mensaje
@uriChat = http://localhost:8000/api/chat
@uriParticipante = http://localhost:8000/api/participante

POST {{uriMensaje}}/enviar/5
Content-Type: application/json

{
  "id_emisor": 9,
  "contenido": "probando el pruebas"
}

###
POST {{uriMensaje}}/group/9
Content-Type: application/json

{
  "id_emisor": 2,
  "contenido": "prueba de mensaje privado"
}

###
POST {{uriMensaje}}/read/5
Content-Type: application/json

{
  "id_usuario": 9
}

###

GET {{uriMensaje}}/read/chat/4
Content-Type: application/json



###
POST {{uriChat}}/create
Content-Type: application/json

{
  "nombre_chat": "aaaa",
  "id_creador": 4
}

###
POST {{uriParticipante}}/agregar/4
Content-Type: application/json

{
  "id_usuario": 4
}
###
POST {{uriParticipante}}/eliminar/4
Content-Type: application/json

{
  "id_usuario": 6,
  "id_admin": 4
}
###