@uriUsuario = http://localhost:8000/api/usuario

GET {{uriUsuario}}/read
Content-Type: application/json

###

POST {{uriUsuario}}/create
Content-Type: application/json

{
  "nombre_usuario": "nauian",
  "nombre_completo": "Ian Portuguez",
  "telefono": "45125836",
  "correo": "iannaun@gmail.com",
  "contrasenna": "123456",
  "foto_perfil": "",
  "estado": "Activo"
}

###

PUT {{uriUsuario}}/update/6
Content-Type: application/json

{
  "nombre_usuario": "xXIan_InsanoXx",
  "nombre_completo": "",
  "telefono": "",
  "correo": "",
  "contrasenna": "",
  "foto_perfil": "",
  "estado": ""
}