@uriUsuario = http://localhost:8000/api/usuario

GET {{uriUsuario}}/read
Content-Type: application/json

###

POST {{uriUsuario}}
Content-Type: application/json

{
  "nombre_usuario": "Luisini",
  "nombre_completo": "Luis Lopez Hernandez",
  "telefono": "727521812",
  "correo": "luisihi@gmail.com",
  "contrasenna": "luis123",
  "foto_perfil": "",
  "estado": "q"
}

###

PUT {{uriUsuario}}/1
Content-Type: application/json

{
  "nombre_usuario": "",
  "nombre_completo": "",
  "telefono": "43232412",
  "correo": "",
  "contrasenna": "",
  "foto_perfil": "",
  "estado": ""
}